// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getEnv(key: string): string | undefined {
  // Vite build-time replacement (client bundle)
  if (typeof import.meta !== 'undefined' && import.meta.env) {
    const val = (import.meta.env as Record<string, string>)[key];
    if (val) return val;
  }
  // Cloudflare Workers / SSR: env is injected via globalThis
  if (typeof globalThis !== 'undefined') {
    const val = (globalThis as Record<string, string>)[key];
    if (val) return val;
  }
  return undefined;
}

function createSupabaseClient() {
  const SUPABASE_URL =
    getEnv('VITE_SUPABASE_URL') ||
    getEnv('SUPABASE_URL');
  const SUPABASE_PUBLISHABLE_KEY =
    getEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
    getEnv('SUPABASE_PUBLISHABLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('Supabase variables missing, using placeholder to avoid crash');
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder', {
      auth: { persistSession: false, autoRefreshToken: false },
    });
  }

  const isBrowser = typeof window !== 'undefined';

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isBrowser ? localStorage : undefined,
      persistSession: isBrowser,
      autoRefreshToken: isBrowser,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
